[package]
name = "remote-keyboard-client"
version = "0.1.0"
authors = ["Jonathan Nilsson <lord.jonil@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["winuser"] }
gilrs = "0.6"